#+AUTHOR: Bill Chambers :: StudentID:25912237
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}

* Problem 5

From the previous problem we proved that if B is a positive definite matrix, then all the diagonal values have to be positive. If we repeat that proof along with the assertion that for p.s.d. x^T Ax \geq 0 we prove that all diagonal values in the p.s.d. matrix are greater than or equal to 0.

Using that, we can see that if we extract the minimum value from the diagonal of the lowest p.s.d. matrix B, then we will extract a 0 value (and no less) we will call that \beta.
$$ \beta = 0 $$

Secondly if we extract the minimum value from the smallest possible matrix of \gamma I, that has to necessarily be positive if \gamma > 0. We'll call that \gamma* given that \gamma* > 0.
$$ \gamma* > 0 $$

From these definitions,

$$ \beta + \gamma* > 0 $$

Since there are the minimum values along the diagonals, we know that all other values are greater than or equal to the above values. We have therefore proved that all values along the diagonal in the resulting matrix C are positive.


Now we can apply the proof from the previous problem, that for all non-zero x, x^T Cx must be greater than 0. Our newly created matrix (C) satisfies this requirement because the only way that X^T Cx would be \leq 0 would be if one of the diagonal elements was 0 or negative which we just proved is impossible.
